### ISSUE TITLE
ignore functions or anything except valid object?

### ISSUE THREAD

**Issue by thammin** [thammin/freemarker-to-json2.js#3]
like this:
```yaml: 
util:
  __methods:
    - 
      name: getCurrentDate
      value: 2017-02-11T22:00:01+09:00
```
